
  <div class="row">
  <center><h4 class="text-center"><strong>GASTROINTESTINAL MOTILITY</strong></h4>  </center>
    <div class="col-sm-12">
    <p class="text-justify">GI motility refers to peristalsis, the smooth muscle contractions that propel digestive contents along the GI tract. Peristaltic motor activity of the gut is an essential activity for digestion and absorption of nutrients to sustain life. These rhythms are critical during and after meals to maximize contact of nutrients with villous surface area for absorption.</p>
	<p class="text-justify">Motility is controlled by the enteric nervous system(ENS),or “gutbrain”,a network of over 100million neurons embedded in the lining of the GI tract. Although the ENS is influenced by the central brain, it functions independently as a branch of the autonomic nervous system. The neurons within the ENS communicate using many of the neurotransmitters found in the brain; however, their local roles in the GI tract are to regulate smooth muscle activity. <b>The most important regulators of digestive motility are Serotonin, Acetylcholine  &  Dopamine.</b></p>
	<p class="text-justify">Dopamine decreases the Acetylcholine level while Seroton inincreases Acetylcholine level, therefore <b>dopaminergic and serotonergic activity balances the gut motility.</b></p>
	<p class="text-justify">Dopamine, while acting through specific dopaminergic receptors, inhibits lower esophageal sphincter(LES) pressure and gastroduodenal motility observed from the esophagus to the  colon.</p>
	<p class="text-justify"><b>Serotonin</b>  is a  multifarious  neurotransmitter,  with  many  functions. Excess  amounts of serotonin cause relaxation and sedation. Chemical name of serotonin is 5-hydroxytryptamine (5-HT).Serotonin is found to have a positive effect in the motor functions of the GI tract. Over 95% of the body’s total serotonin is generated by the GI tract, where it coordinates motility by binding to serotonin type 4 (5 HT) receptors. Once activated, these receptors stimulate the release of acetylcholine in tone uromuscular junctions, resulting in coordinated peristalsis, vascular tone and secretion. Serotonin dysfunction is involved in the pathophysiology of a number of functional GI disorders, such as Chronic Constipation, Irritable Bowel Syndrome, Diabetic Gastroparesis, Functional Dyspepsia and GERD. 5-HTP supports coordinated motility of the upper and lower GI tract,  in  part  by  supporting  5-HT<sub>4</sub> activity</p>
	<p class="text-justify"><b>In  the  GI  system  dopamine  delays  gastric  emptying  &  esophageal  motility  as it inhibits acetylcholine.</b></p>
	<h3 class="text-center"><strong>UPPER-GUTMOTILITYDISORDERS</strong></h3>
	<h4><strong>1. FUNCTIONAL DYSPEPSIA:</strong></h4>
	<p class="text-justify">Dyspepsia is a group of symptoms of the epigastric region including bloating, fullness, early satiety, nausea, belching, vomiting, acid reflux and hyperacidity.</p>
	<p class="text-justify">Dyspepsia can be caused by stress, spicy food & conditions which aggravate excess acid secretion etc.</p>
	<p class="text-justify">It is clear that dyspepsia and functional dyspepsia in particular are common conditions globally, affecting most populations, regardless of location. Risk factors for functional dyspepsia have been shown to include females and underlying psychological disturbances, whilst environmental / lifestyle habits such as poor socio-economic status, smoking, increased caffeine intake and ingestion of non-steroidal anti-inflammatory drugs appear to be more relevant to uninvestigated dyspepsia.</p>
	<h4><strong>2.  GERD:</strong></h4>
	<h5><strong>Gastro-Esophageal Reflux Disease (GERD)</strong></h5>
	<p class="text-justify">GERD is defined as chronic symptom or mucosal damage produced by the abnormal reflux of gastric contents into the esophagus. Reflux esophagitis refers to a subgroup of GERD patients with histopathologically demonstrated characteristic changes in the esophageal mucosa.</strong></p>
	<img src="<?php echo base_url().'tutorial/common/'; ?>gerd.png" class="img-responsive center-block">
	<p class="text-justify"><b>Treatment:</b></p>
	<p class="text-justify">The various agents currently used for treatment of GERD include Mucoprotective substances, Antacids, H Blockers,  Prokinetics  PPIs.</p>
	<h4><strong>3.  LARYNGOPHARYNGEAL REFLUX (LPR):</strong></h4>
	<p class="text-justify">Laryngopharyngeal reflux (LPR) is the backflow of stomach contents up the esophagus and into the  throat.</p>
	<p class="text-justify">There are two sphincter muscles located in the esophagus: The lower esophageal sphincter (LES) and the upper esophageal sphincter (UES). When the lower esophageal sphincter is not functioning properly, there is a backflow of stomach acid into the esophagus. This condition is called as GERD (gastro esophageal reflux disease).</p>
	<p class="text-justify">As with the lower esophageal sphincter, if the upper esophageal sphincter doesn’t function properly, acid that has back flowed into the esophagus is allowed into the throat and larynx. When this happens, it’s called Laryngopharyngeal Reflux(LPR).</p>
	<p class="text-justify">LPR is different than gastro esophageal reflux disease(GERD) as Patients with GERD are usually suffer from heartburn and esophagitis while the patients with LPR do suffer from heartburn  or  esophagitis  (12%).</p>
	<ul>
		<h5><b>Symptoms:</b></h5>
		<li>Hoarseness</li>
		<li>Frequent throat clearing</li>
		<li>Globus  Pharyngeus  (sensation  of  a  lump  in  the  throat)</li>
		<li>Chronic Cough</li>
		<li>Bad/bitter taste in mouth</li>
		<li>Sore throat</li>
	</ul>
	<ul>
		<h5><b>Treatment:</b></h5>
		<li>Life style changes</li>
		<li>Diet modifications</li>
		<li>Medications: To reduce stomach acid or to promote normal motility. These can include Proton Pump Inhibitors, Histamine Receptor Antagonists and Prokinetic agents.</li>
		<li>Surgery to prevent reflux</li>
	</ul>
	<h3 class="text-center"><strong>MID-GUTMOTILITYDISORDERS</strong></h3>
	<h4><strong>GASTROPARESIS:</strong></h4>
		<p class="text-justify">Gastroparesis means paralysis of the muscles of the stomach which results in delayed emptying  of  the  food  from  the  stomach  to  the  small  intestine.</p>
		<p class="text-justify">Gastroparesis is more common in diabetic patients because of the damage of the nerves which generally control the stomach muscles. So it is also called as <b>Diabetic Gastroparesis</b></p>
		<p class="text-justify">Ordinarily, strong muscular contractions propel food on its long and convoluted journey through the digestive tract. But in gastroparesis, the muscles in the wall of the stomach work poorly or not at all, preventing the stomach from emptying properly. This can interfere with digestion, cause nausea and vomiting, and play havoc with blood sugar levels and nutrition</p>
	<h5><strong>Treatment</strong></h5>
	<p class="text-justify">Controlling diabetes or any other underlying condition that may be causing gastroparesis is the first step in treating the condition. Beyond this, dietary changes and medications that increase stomach contractions have long been the mainstay of gastroparesis therapy.</p>
	<p class="text-justify">Doctors usually prescribe two types of drugs to treat gastroparesis – anti-emetics which help control nausea and vomiting and prokinetics, which stimulate contractions of the stomach  muscles..</p>
	<h3 class="text-center"><strong>LOWER-GUTMOTILITYDISORDERS</strong></h3>
	<h4><strong>IRRITABLE BOWEL SYNDROME (IBS) WITH CONSTIPATION:</strong></h4>
	<p class="text-justify">Irritable bowel syndrome (IBS) is a chronic gastrointestinal disorder of unknown cause. Common symptoms include abdominal cramping or pain, bloating and gassiness and altered bowel habits. Irritable bowel syndrome has also been called spastic colon, functional bowel disease and mucous colitis.</p>
	<p class="text-justify">Irritable bowel syndrome is not contagious, inherited, or cancerous.It is estimated that 20% of population  have  symptoms  of  IBS.  It  occurs  more  often  in  women than in men and  the  onset  occurs  before  the  age  of  35  in  about  half  of  the  cases.</p>
	<p class="text-justify">Chronic <b>constipation</b> caused by motility disturbances of the lower digestive tract, for many begin in childhood and persists into adulthood. <b>Constipation</b> for those with digestive motility problems is much more than a mere nuisance.</p>
	<h3 class="text-center"><strong>TREATMENT OF GI MOTILITY DISORDERS</strong></h3>
	<p class="text-justify">The motility disorders are also associated with increased levels of acid seretion. Thus there is need of combination therapy of a PPI+Prokinetic which will not only correct the motility but also control excessive acid secretion.</p>
	<h5><strong>Prokinetic agents:</strong></h5>
	<p class="text-justify">Prokinetic agents are  drugs  that  enhance  motor  activity  of</p>
	<ol>
		<li><b>D<sub>2</sub> Receptor Antagonists:</b>
		<p class="text-justify">Metoclopramide, Cisapride, Itopride, Bromopride, Domperidone, Levosulpiride</p></li>
		<li><b>5HT<sub>4</sub> Receptor Agonists:</b>
		<p class="text-justify">A treatments may help a sufferer to cope combination of the smooth muscle (characteristic of GI tract). Although potentially beneficial for improving the strength of esophageal peristalsis,the resting pressure of the LES, and the strength of gastric contractions, it appears that the most important influence of available prokinetic agents is on gastric motility.</p>
		<p class="text-justify"><b>Classification:</b> Cinitapride, Levosulpiride.</p>
		</li>
		<li><b>5HT<sub>3</sub> Receptor Antagonists:</b>
			<p class="text-justify">Mosapride, Cisapride.</p>
		</li>
	</ol>
	<h3 class="text-center"><strong>LEVOSULPIRIDE</strong></h3>
	<div class="col-sm-3">
		<img src="<?php echo base_url().'tutorial/common/'; ?>Levosulpiride.png" class="img-responsive center-block">
	</div>
	<div class="col-sm-9">
		<p class="text-justify">Levosulpiride is a levorotatory enantiomer of sulpiride, a substituted benzamide, chemically it is (S)-(-) Sulpiride; (S)-5-Aminosulfonyl-N-[(1-ethyl-2-pyrrolidinyl)methyl]-2-methoxybenzamide.<b>Levosulpiride is reported to be a selective antagonist of dopamine D2 receptors having activity on both central and peripheral levels.</b>It is a prokinetic & used in the treatment of dyspepsia, irritable bowel syndrome.</p>
		<p class="text-justify">It is a prokinetic agent which increases the lower esophageal sphincter pressure more rapidly and effectively than other therapeutic agents.</p>
	</div>
	<h4>&nbsp;&nbsp;&nbsp;&nbsp;</h4>
	<h4>&nbsp;&nbsp;&nbsp;&nbsp;</h4>
		<h4><strong>MECHANISM OF ACTION:</strong></h4>
		<h5><strong>As a Prokinetic:</strong></h5>
		<p class="text-justify">The prokinetic effect of Levosulpiride is mediated through the blockade of enteric(neuronal and muscular)inhibitory dopamine D2 receptors.It also acts as a moderate agonist at the 5-HT<sub>4</sub> receptor. The serotonergic (5-HT) component of Levosulpiride enhances its therapeutic efficacy in gastrointestinal disorders.This property together  with antagonism at D2  receptors,  may  contribute  to  its  gastrointestinal  prokinetic  effect.</p>
		<h5><strong>As an Antiemetic:</strong></h5>
		<p class="text-justify">The anti emetic effect of Levosulpiride is due to inhibition of dopamine transmission and antagonism with D2 receptors of the neurons in the area postrema of the vomiting center (IV ventricle) or chemoreceptor trigger zone in the CNS, blocking the inhibitory effect of dopamine on cholinergic neurons and therefore permitting a sustained cholinergic induced contraction of smooth muscle cell in the myenteric plexus of the esophagus, stomach  and  intestine.</p>
		<h4><strong>PHARMACOKINETICS</strong></h4>
		<p class="text-justify"><b>Absorption:</b> Oral bioavailability is about 30%; peak plasma concentrations are achieved after  about 3  hrs.</p>
		<p class="text-justify"><b>Plasma half-life:</b>  9.7 hrs (oral); 4.3 hrs(IV).</p>
		<p class="text-justify"><b>Excretion:</b> Mainly via urine.</p> 
		<p class="text-justify"><b>Side  Effects:</b> Amenorrhoea, Gynaecomastia, Galactorrhoea.</p>	 
		<p class="text-justify"><b>Special Precautions:</b>
		May impair ability to drive or operate machinery.</p>
		<p class="text-justify"><b>Drug Interactions:</b>
		Reduced bioavailability with Sucralfate, Aluminium and magnesium contain in antacids. Effect on GI motility may be antagonized by anticholinergic agents, narcotics and
		analgesics.</p>
		<p class="text-justify"><b>Dosage:</b>
		Gastro-esophageal reflux disease, Irritable bowel syndrome, Dyspepsia
		<ul>
		<li><b>Adult:</b> 25 mgTID or 75 mg OD with meals.</li>
		<li><b>Elderly:</b> Dose reductions may be necessary.</li>
		</ul>
		</p>
		<p class="text-justify">Contraindications:
		<ul>
		<li><b>Pregnancy:</b> Caution when used during pregnancy</li>
		<li><b>Lactation:</b> Caution when used during lactation</li>
		</ul>
		</p>
		<h4><strong>Levosulpiride vs other Prokinetics</strong></h4>
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-condensed">
				<thead class="thead-default">
					<tr>
						<th class="text-center">Parameters</th>
						<th class="text-center">Levosulpiride</th>
						<th class="text-center">Domperidone</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>MOA</td>
						<td>D2  receptor  antagonist & 5HT4  receptors agonist</td>
						<td>D2  receptor antagonist</td>
					</tr>
					<tr>
						<td>Anti-emetic  action</td>
						<td>&#10003;</td>
						<td>&#10003;</td>
					</tr>
					<tr>
						<td>ProkineticEfficacy</td>
						<td>More</td>
						<td>Less</td>
					</tr>
					<tr>
						<td>Site  of Prokinetic action</td>
						<td>EntireGut</td>
						<td>MainlyUpper  Gut</td>
					</tr>
					<tr>
						<td>Role in IBS with Constipation</td>
						<td>Yes</td>
						<td>No</td>
					</tr>
				</tbody>
			</table>
		</div>
		<h3 class="text-center"><strong>PANTIN-L</strong></h3>
		<h4><strong>COMPOSITION</strong></h4>
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-condensed">
				<thead class="thead-default">
					<tr>
						<th class="text-center">Brand</th>
						<th class="text-center">Composition</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>PANTIN-L</td>
						<td>Eachhardgelatincapsulecontains: <br/>
						Pantoprazole Sodiumsesquihydrate
						equivalent to Pantoprazole ……... 40 mg
						(asentericcoatedpellets),
						<br/>
						Levosulpiride …………...  75  mg
						(assustainedreleasepellets)
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<h4><b>Indications</b></h4>
			<ul>
				<li>Gastro-esophageal reflux disease(GERD)with or without esophagitis</li>
				<li>Functional dyspepsia</li>
				<li>Gastroparesis</li>
				<li>Irritable bowel syndrome with constipation</li>
				<li>Laryngopharyngeal Reflux Disorder (LPRD)</li>
				<li>Constipation</li>
				<li>Reflux Esophagitis</li>
				<li>Ulcer</li>
			</ul> 
		<h4><b>Dosage :</b></h4><p>One capsule once a day</p>
		<h4><b>Rationale for the combination:</b></h4>
			<ul>
				<li>Gastric motility disorders are associated with increased levels of gastric acid secretion and delayed gastric emptying with nausea and vomiting.Hence there is need for the combination of PPI and Prokinetic Agent</li>
				<li>Pantoprazole in Pantin Lcontrols excess of acid secretion and Levosulpiride in Pantin L corrects dysmotility with nausea and vomiting</li>
				<li>Pantin L is effective and well tolerated in Functional Dyspepsia accompanied with delayed gastric emptying and IBS</li>
			</ul>
		<h4><b>Unique Features of Pantin L</b></h4>
			<ul>
				<li>Pantin L is available in Capsule (Multiple pellet technology) that ensures Faster absorption, Rapid action, Better efficacy, Minimal GI side effects.</li>
				<li>Pantin L is the most economical brand of Pantoprazole and Levosulpiride.</li>
				<li>Pantin L comes from Genx- basic manufacturers of Pantoprazole and Levosulpiride in India.</li>
			</ul>
		<p class="text-justify">Thus Pantoprazole reduces acids ecretion and Levosulpiride corrects dysmotility.</p>
		<p class="text-justify">Besides this combination also provides OD dosage convenience and thus enhances patient compliance.</p>
		<h4><b>COMMUNICATION HIGHLIGHTS</b></h4>
		<h5><b>GPs/Cons.Physicians/Gastro’s</b></h5>
		<ul>
			<li>To strongly communicate – Rising stress levels and acidity can lead to GI dysmotility where 2 ka dum Pantin L is the need of the hour.</li>
			<li>To emphasize that Levosulpiride offers reduction of gastric emptying time</li>
			<li>To strongly communicate the benefits of Pantoprazole being the trusted PPI</li>
		</ul>
		<h5><b>Surgeons/Orthopaedicians:</b></h5>
		<ul>
			<li>To highlight the advantages of 2 ka Dum Pantin L in Ulcer, constipation, reflux esophagitis and Functional dyspepsia.</li>
			<li>To communicate that levosulpiride present in Pantin L stimulates gastric motor activity during the digestive phase.</li>
		</ul>
		<h4><b>Pantin Premiere League:</b></h4>
		<h5><b>Rules of the game- April- June 19</b></h5>
		<ul>
			<li>Every HQ is eligible to participate in the league in the first 3 months April- June 19.</li>
			<li>Qualifying criteria for further play in the game is to reach a base of 100 PHPM for each and every HQ</li>
			<li>Each HQ will play league matches within the region for the month of April- June 19</li>
			<li>Fixtures of the matches will be mailed to all RM’s by 30th March . RM will fix matches within his HQ’S</li>
			<li>Eligibility as well as qualifying criteria is 100 PHPM at all HQ’S</li>
			<li>Results will be mailed by 5th of every month along with next month fixtures to RM</li>
		</ul>
  </div>
</div>
